"""Build a new-uploader UGC v1.30 small-sign discovery pack."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];SOURCE=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.29.0.json";DESTINATION=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.30.0.json"
B={
"en":["my union apprentice holding training rights banner local workshop","our neighborhood cooks holding fair rent signs community market","my college roommate holding climate petition banner campus event","our local caregivers holding paid leave placard town hall gathering","my friend holding accessible bus sign community ride","our small shopkeepers group holding tax relief banner street meeting","my neighbor holding safe park sign local cleanup","our student volunteers holding meal aid banner school drive","my coworker holding weekend pay sign local warehouse action","our block residents holding streetlight petition evening gathering","my family holding clinic access banner health walk","our local delivery group holding rain pay signs depot meetup","my friend holding tenant rights placard building courtyard","our community choir holding arts funding sign local festival","my classmates holding exam fairness banner school gate","our small union group holding overtime petition factory shift","my neighbor holding clean river sign riverside event","our parents group holding library hours banner weekend meeting","my coworker holding safety gear placard worksite entrance","our volunteers holding shelter support banner community collection"],
"es":["mi aprendiz sindical con pancarta de derechos de formación taller local","nuestros cocineros vecinales con carteles de alquiler justo mercado comunitario","mi compañero de universidad con pancarta climática evento de campus","nuestros cuidadores locales con cartel de permiso pagado reunión municipal","mi amigo con cartel de autobús accesible paseo comunitario","nuestro pequeño grupo de comerciantes con pancarta fiscal reunión de calle","mi vecino con cartel de parque seguro limpieza local","nuestros estudiantes voluntarios con pancarta de comidas actividad escolar","mi compañero con cartel de pago de fin de semana acción de almacén","nuestros residentes de bloque con petición de alumbrado reunión nocturna","mi familia con pancarta de acceso a clínica caminata de salud","nuestro grupo local de reparto con carteles de pago de lluvia reunión de depósito","mi amigo con cartel de derechos de inquilino patio de edificio","nuestro coro comunitario con pancarta de fondos de arte festival local","mis compañeros con pancarta de exámenes justos puerta de escuela","nuestro pequeño grupo sindical con petición de horas extra turno de fábrica","mi vecino con cartel de río limpio evento junto al río","nuestro grupo de padres con pancarta de horarios de biblioteca reunión de fin de semana","mi compañero con cartel de equipo de seguridad entrada de obra","nuestros voluntarios con pancarta de apoyo de refugio colecta comunitaria"],
"fr":["mon apprenti syndical avec banderole droits formation atelier local","nos cuisiniers quartier avec pancartes loyer équitable marché communauté","mon camarade université avec banderole climat événement campus","nos aidants locaux avec pancarte congé payé rassemblement mairie","mon ami avec pancarte bus accessible balade communauté","notre petit groupe commerçants avec banderole allégement fiscal réunion rue","mon voisin avec pancarte parc sûr nettoyage local","nos étudiants bénévoles avec banderole repas action école","mon collègue avec pancarte paie week-end action entrepôt","nos résidents immeuble avec pétition éclairage rassemblement soir","ma famille avec banderole accès clinique marche santé","notre groupe livraison local avec pancartes paie pluie rencontre dépôt","mon ami avec pancarte droits locataires cour immeuble","notre chorale communauté avec banderole financement arts festival local","mes camarades avec banderole examens équitables portail école","notre petit groupe syndical avec pétition heures supplémentaires équipe usine","mon voisin avec pancarte rivière propre événement rive","notre groupe parents avec banderole horaires bibliothèque réunion week-end","mon collègue avec pancarte équipement sécurité entrée chantier","nos bénévoles avec banderole soutien refuge collecte communauté"]}
A={"en":["#shorts","reel","phone video","vertical video","mobile video"],"es":["shorts","reel","vídeo móvil","vídeo vertical","video móvil"],"fr":["shorts","reel","vidéo mobile","vidéo verticale","vidéo téléphone"]};P={"en":["one person","two people"],"es":["una persona","dos personas"],"fr":["une personne","deux personnes"]};W={"en":"holding protest sign banner","es":"con cartel pancarta de protesta","fr":"avec pancarte banderole de protestation"}
def main():
 d=json.loads(SOURCE.read_text(encoding="utf-8"));qs=[]
 for lang,items in B.items():
  i=0
  for b in items:
   for p in P[lang]:
    i+=1;a=A[lang][(i-1)%5];act=f"{p} {W[lang]} {b}";qs.append({"query_id":f"sav130-sign-banner-{lang}-{i:02d}","campaign_id":"sign_action_v1","subtype":"举牌/横幅","lang":lang,"query":f"{act} {a}","source_anchor":a,"source_pool":"mobile_adjacent","action_or_scene_term":act,"rationale_zh":"面向新UGC上传者的第一人称、本地社区/工会/校园/家庭活动组合；每条含手机或短视频锚点和1至5人举牌动作，保持uploader cap、来源门、原始0.440最大相似度和全部硬排除。"})
 assert len(qs)==120
 c=json.dumps(qs,ensure_ascii=False,sort_keys=True,separators=(",",":"))+"\n";d.update({"query_pack_version":"sign_action_v1.qp.v1.30.0","queries":qs,"content_sha256":hashlib.sha256(c.encode()).hexdigest(),"created_at":"2026-08-28T17:00:00Z","frozen_at":"2026-08-28","frozen_by":"derived_from_frozen_user_concepts","revision_from":"sign_action_v1.qp.v1.29.0","revision_reason":"用户要求120条不与v1.28/v1.29复用的UGC新上传者查询；保持uploader cap、1至5人、来源门、0.440最大相似度和150 probe上限。"});DESTINATION.write_text(json.dumps(d,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
if __name__=="__main__":main()
