"""Build a fresh v1.25 120-query small-sign pack after reused-text exhaustion."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; SOURCE=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.24.0.json"; DESTINATION=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.25.0.json"
B={
"en":["street food vendor holding licensing reform sign outside permits office","two laundry workers holding health insurance banner outside service depot","small court interpreters group holding access petition courthouse annex","one park ranger holding conservation funding placard visitor center","two hotel cooks holding kitchen safety banner restaurant district","small refugee families group holding housing appeal signs resettlement office","one airport baggage handler holding injury prevention sign terminal gate","two school counselors holding mental health banner district office","small disability advocates group holding captioning access signs media center","one farm laborer holding heat protection placard growers association","two barber workers holding fair rent banner shopfront row","small college tutors group holding wage signs learning center","one street cleaner holding equipment repair sign sanitation garage","two warehouse packers holding overtime banner fulfillment center","small indigenous advocates group holding land rights signs heritage office","one dialysis nurse holding staffing petition clinic lobby","two community volunteers holding food pantry banner relief center","small musicians group holding rehearsal space signs arts warehouse","one childcare parent holding subsidy placard family court entrance","two factory inspectors holding safety rules banner industrial agency"],
"es":["vendedor ambulante con cartel de reforma de permisos frente a oficina","dos trabajadores de lavandería con pancarta de seguro médico frente a depósito","grupo pequeño de intérpretes judiciales con petición de acceso en anexo del juzgado","un guardaparque con cartel de conservación frente a centro de visitantes","dos cocineros de hotel con pancarta de seguridad en distrito de restaurantes","grupo pequeño de familias refugiadas con carteles de vivienda en oficina de reasentamiento","un manejador de equipaje con cartel de prevención de lesiones en terminal","dos consejeros escolares con pancarta de salud mental en oficina distrital","grupo pequeño por discapacidad con carteles de subtítulos en centro de medios","un trabajador agrícola con cartel de protección contra calor en asociación","dos barberos con pancarta de alquiler justo en fila de tiendas","grupo pequeño de tutores universitarios con carteles de salario en centro educativo","un limpiador de calles con cartel de reparación de equipo en garaje","dos empaquetadores de almacén con pancarta de horas extra en centro logístico","grupo pequeño indígena con carteles de tierra en oficina patrimonial","una enfermera de diálisis con petición de personal en vestíbulo de clínica","dos voluntarios comunitarios con pancarta de despensa en centro de ayuda","grupo pequeño de músicos con carteles de espacio de ensayo en almacén de artes","un padre de guardería con cartel de subsidio en entrada de tribunal familiar","dos inspectores de fábrica con pancarta de normas de seguridad en agencia industrial"],
"fr":["vendeur rue avec pancarte réforme permis devant bureau licences","deux employés blanchisserie avec banderole assurance santé devant dépôt","petit groupe interprètes tribunal avec pétition accès annexe tribunal","un garde parc avec pancarte financement conservation centre visiteurs","deux cuisiniers hôtel avec banderole sécurité quartier restaurants","petit groupe familles réfugiées avec pancartes logement bureau réinstallation","un bagagiste aéroport avec pancarte prévention blessures portail terminal","deux conseillers école avec banderole santé mentale bureau district","petit groupe handicap avec pancartes sous-titrage centre médias","un ouvrier agricole avec pancarte protection chaleur association producteurs","deux barbiers avec banderole loyer équitable rangée magasins","petit groupe tuteurs université avec pancartes salaire centre apprentissage","un nettoyeur rue avec pancarte réparation matériel garage nettoyage","deux emballeurs entrepôt avec banderole heures supplémentaires centre logistique","petit groupe autochtone avec pancartes droits terre bureau patrimoine","une infirmière dialyse avec pétition personnel hall clinique","deux bénévoles quartier avec banderole banque alimentaire centre aide","petit groupe musiciens avec pancartes espace répétition entrepôt arts","un parent garderie avec pancarte subvention entrée tribunal famille","deux inspecteurs usine avec banderole règles sécurité agence industrielle"]}
A={"en":["phone video","vertical video","short video","mobile video","#shorts"],"es":["vídeo móvil","vídeo vertical","video corto","vídeo móvil","shorts"],"fr":["vidéo mobile","vidéo verticale","vidéo courte","vidéo mobile","shorts"]};P={"en":["one person holding","two people holding"],"es":["una persona con","dos personas con"],"fr":["une personne avec","deux personnes avec"]};W={"en":"protest sign banner","es":"cartel pancarta de protesta","fr":"pancarte banderole de protestation"}
def main():
 d=json.loads(SOURCE.read_text(encoding="utf-8"));qs=[]
 for lang,items in B.items():
  i=0
  for base in items:
   for p in P[lang]:
    i+=1;a=A[lang][(i-1)%5];act=f"{p} {W[lang]} {base}";qs.append({"query_id":f"sav125-sign-banner-{lang}-{i:02d}","campaign_id":"sign_action_v1","subtype":"举牌/横幅","lang":lang,"query":f"{act} {a}","source_anchor":a,"source_pool":"mobile_adjacent","action_or_scene_term":act,"rationale_zh":"从冻结的1至5人直接举牌/横幅定义派生新的职业、抗议主题、机构与街道/设施场景；每条含手机或短视频锚点，保持来源门、原始0.440多查询最大相似度门和全部硬排除。"})
 assert len(qs)==120
 c=json.dumps(qs,ensure_ascii=False,sort_keys=True,separators=(",",":"))+"\n";d.update({"query_pack_version":"sign_action_v1.qp.v1.25.0","queries":qs,"content_sha256":hashlib.sha256(c.encode()).hexdigest(),"created_at":"2026-08-28T12:00:00Z","frozen_at":"2026-08-28","frozen_by":"derived_from_frozen_user_concepts","revision_from":"sign_action_v1.qp.v1.24.0","revision_reason":"v1.24复用文本的下一probe tranche未新增下载；恢复120条不复用v1.18-v1.23文本的新组合，保持1至5人、来源门、0.440最大相似度和150 probe上限。"});DESTINATION.write_text(json.dumps(d,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
if __name__=="__main__":main()
