"""Build fresh first-person local-UGC small-sign queries for new uploaders."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];SOURCE=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.28.0.json";DESTINATION=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.29.0.json"
B={
"en":["my local union crew holding contract banner workshop gate","our block tenants holding heat repair signs apartment courtyard","my campus classmates holding scholarship placard college quad","our neighborhood parents holding crossing guard banner school corner","my volunteer team holding food pantry sign community pickup","our local nurses holding clinic hours placard health fair","my coworker holding paycheck complaint sign retail strip","our small renters club holding mold repair banner housing meetup","my friend holding library funding sign town gathering","our neighborhood cyclists holding safe street signs bike ride","my family holding clean playground banner park cleanup","our local shop workers holding break rights sign storefront","my class group holding student loan placard campus lawn","our tenants association holding landlord notice banner building entrance","my coworkers holding overtime signs shift change","our community gardeners holding water access placard allotment gate","my local artists holding studio space banner street festival","our small transit group holding bus route signs stop meetup","my neighbor holding noise complaint placard block gathering","our community volunteers holding disaster aid banner relief drive"],
"es":["mi equipo sindical local con pancarta de contrato en puerta de taller","nuestros inquilinos de bloque con carteles de calefacción en patio","mis compañeros de campus con cartel de becas en plaza universitaria","nuestros padres vecinales con pancarta de cruce seguro en esquina escolar","mi equipo voluntario con cartel de despensa en recogida comunitaria","nuestras enfermeras locales con cartel de horarios en feria de salud","mi compañero con cartel de queja de pago en zona comercial","nuestro pequeño club de inquilinos con pancarta de moho en reunión","mi amigo con cartel de fondos de biblioteca en reunión local","nuestros ciclistas vecinales con carteles de calle segura en paseo","mi familia con pancarta de parque limpio en limpieza local","nuestros trabajadores de tienda con cartel de descansos en escaparate","mi grupo de clase con cartel de deuda estudiantil en césped de campus","nuestra asociación de inquilinos con pancarta de aviso de casero en entrada","mis compañeros con carteles de horas extra en cambio de turno","nuestros jardineros comunitarios con cartel de agua en puerta de huerto","mis artistas locales con pancarta de espacio de estudio en festival","nuestro pequeño grupo de transporte con carteles de ruta en parada","mi vecino con cartel de ruido en reunión de bloque","nuestros voluntarios comunitarios con pancarta de ayuda en actividad local"],
"fr":["mon équipe syndicale locale avec banderole contrat portail atelier","nos locataires immeuble avec pancartes chauffage cour appartement","mes camarades campus avec pancarte bourses place collège","nos parents quartier avec banderole passage sûr coin école","mon équipe bénévoles avec pancarte banque alimentaire collecte communauté","nos infirmières locales avec pancarte horaires foire santé","mon collègue avec pancarte plainte paie rue commerces","notre petit club locataires avec banderole moisissure réunion logement","mon ami avec pancarte financement bibliothèque rassemblement ville","nos cyclistes quartier avec pancartes rue sûre balade vélo","ma famille avec banderole aire jeux propre nettoyage parc","nos employés magasin avec pancarte pauses devant boutique","mon groupe classe avec pancarte dette étudiante pelouse campus","notre association locataires avec banderole avis propriétaire entrée immeuble","mes collègues avec pancartes heures supplémentaires changement équipe","nos jardiniers communauté avec pancarte accès eau portail jardin","mes artistes locaux avec banderole espace studio festival rue","notre petit groupe transport avec pancartes ligne bus rencontre arrêt","mon voisin avec pancarte plainte bruit rassemblement bloc","nos bénévoles communauté avec banderole aide catastrophe activité quartier"]}
A={"en":["#shorts","reel","phone video","vertical video","mobile video"],"es":["shorts","reel","vídeo móvil","vídeo vertical","video móvil"],"fr":["shorts","reel","vidéo mobile","vidéo verticale","vidéo téléphone"]};P={"en":["one person","two people"],"es":["una persona","dos personas"],"fr":["une personne","deux personnes"]};W={"en":"holding protest sign banner","es":"con cartel pancarta de protesta","fr":"avec pancarte banderole de protestation"}
def main():
 d=json.loads(SOURCE.read_text(encoding="utf-8"));qs=[]
 for lang,items in B.items():
  i=0
  for b in items:
   for p in P[lang]:
    i+=1;a=A[lang][(i-1)%5];act=f"{p} {W[lang]} {b}";qs.append({"query_id":f"sav129-sign-banner-{lang}-{i:02d}","campaign_id":"sign_action_v1","subtype":"举牌/横幅","lang":lang,"query":f"{act} {a}","source_anchor":a,"source_pool":"mobile_adjacent","action_or_scene_term":act,"rationale_zh":"面向新UGC上传者的第一人称、社区/工会/校园/本地活动组合；每条含手机或短视频锚点和1至5人举牌动作，避免新闻、记者、采访表达，保持uploader cap、来源门、0.440最大相似度和全部硬排除。"})
 assert len(qs)==120
 c=json.dumps(qs,ensure_ascii=False,sort_keys=True,separators=(",",":"))+"\n";d.update({"query_pack_version":"sign_action_v1.qp.v1.29.0","queries":qs,"content_sha256":hashlib.sha256(c.encode()).hexdigest(),"created_at":"2026-08-28T16:00:00Z","frozen_at":"2026-08-28","frozen_by":"derived_from_frozen_user_concepts","revision_from":"sign_action_v1.qp.v1.28.0","revision_reason":"用户要求120条不与v1.28复用的第一人称、社区/工会/校园/本地活动UGC查询，保持uploader cap、1至5人、来源门、0.440最大相似度和150 probe上限。"});DESTINATION.write_text(json.dumps(d,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
if __name__=="__main__":main()
