"""Find new UGC uploaders without weakening the small-sign source/task gates."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];SOURCE=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.27.0.json";DESTINATION=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.28.0.json"
B={
"en":["my union coworker holding picket sign local event","our tenant group holding rent banner neighborhood meeting","my campus friend holding tuition sign student action","our community holding clean water placard town event","my coworker holding fair wage sign workplace rally","our parents group holding school safety banner local action","my neighbor holding road repair sign community event","our small climate group holding banner park gathering","my friend holding boycott sign outside local shop","our volunteer group holding food aid banner neighborhood drive","my teacher holding classroom sign school event","our nurses group holding staffing placard local action","my brother holding transit complaint sign bus stop","our student club holding petition banner campus walk","my coworker holding schedule sign warehouse action","our local artists holding funding banner community event","my neighbor holding housing repair sign block meeting","our small workers group holding rights banner factory gate","my friend holding animal welfare sign local event","our community group holding library sign neighborhood action"],
"es":["mi compañero sindical con cartel de piquete evento local","nuestro grupo de inquilinos con pancarta de alquiler reunión vecinal","mi amigo de campus con cartel de matrícula acción estudiantil","nuestra comunidad con cartel de agua limpia evento local","mi compañero con cartel de salario justo protesta laboral","nuestro grupo de padres con pancarta de seguridad escolar acción local","mi vecino con cartel de reparación de calle evento comunitario","nuestro pequeño grupo climático con pancarta reunión de parque","mi amigo con cartel de boicot fuera de tienda local","nuestro grupo voluntario con pancarta de ayuda alimentaria actividad vecinal","mi profesor con cartel de aula evento escolar","nuestro grupo de enfermeras con cartel de personal acción local","mi hermano con cartel de transporte en parada de autobús","nuestro club estudiantil con pancarta de petición paseo de campus","mi compañero con cartel de horario acción de almacén","nuestros artistas locales con pancarta de fondos evento comunitario","mi vecino con cartel de reparación de vivienda reunión de bloque","nuestro pequeño grupo de trabajadores con pancarta de derechos puerta de fábrica","mi amigo con cartel de bienestar animal evento local","nuestro grupo comunitario con cartel de biblioteca acción vecinal"],
"fr":["mon collègue syndical avec pancarte piquet événement local","notre groupe locataires avec banderole loyer réunion quartier","mon ami campus avec pancarte frais action étudiante","notre communauté avec pancarte eau propre événement local","mon collègue avec pancarte salaire équitable action travail","notre groupe parents avec banderole sécurité école action locale","mon voisin avec pancarte réparation rue événement communauté","notre petit groupe climat avec banderole rassemblement parc","mon ami avec pancarte boycott devant magasin local","notre groupe bénévoles avec banderole aide alimentaire action quartier","mon professeur avec pancarte classe événement école","notre groupe infirmières avec pancarte personnel action locale","mon frère avec pancarte transport arrêt bus","notre club étudiants avec banderole pétition marche campus","mon collègue avec pancarte horaires action entrepôt","nos artistes locaux avec banderole financement événement communauté","mon voisin avec pancarte réparation logement réunion immeuble","notre petit groupe travailleurs avec banderole droits portail usine","mon ami avec pancarte bien-être animal événement local","notre groupe communauté avec pancarte bibliothèque action quartier"]}
A={"en":["#shorts","reel","phone video","vertical video","mobile video"],"es":["shorts","reel","vídeo móvil","vídeo vertical","video móvil"],"fr":["shorts","reel","vidéo mobile","vidéo verticale","vidéo téléphone"]};P={"en":["one person","two people"],"es":["una persona","dos personas"],"fr":["une personne","deux personnes"]};W={"en":"holding protest sign banner","es":"con cartel pancarta de protesta","fr":"avec pancarte banderole de protestation"}
def main():
 d=json.loads(SOURCE.read_text(encoding="utf-8"));qs=[]
 for lang,items in B.items():
  i=0
  for b in items:
   for p in P[lang]:
    i+=1;a=A[lang][(i-1)%5];act=f"{p} {W[lang]} {b}";qs.append({"query_id":f"sav128-sign-banner-{lang}-{i:02d}","campaign_id":"sign_action_v1","subtype":"举牌/横幅","lang":lang,"query":f"{act} {a}","source_anchor":a,"source_pool":"mobile_adjacent","action_or_scene_term":act,"rationale_zh":"专门从第一人称、社区/工会/校园/本地活动UGC中寻找新上传者；每条含手机或短视频锚点和1至5人举牌动作，避免新闻、记者、采访表达，保持来源门、0.440最大相似度门与全部硬排除。"})
 assert len(qs)==120
 c=json.dumps(qs,ensure_ascii=False,sort_keys=True,separators=(",",":"))+"\n";d.update({"query_pack_version":"sign_action_v1.qp.v1.28.0","queries":qs,"content_sha256":hashlib.sha256(c.encode()).hexdigest(),"created_at":"2026-08-28T15:00:00Z","frozen_at":"2026-08-28","frozen_by":"derived_from_frozen_user_concepts","revision_from":"sign_action_v1.qp.v1.27.0","revision_reason":"当前>=0.440候选被11个已满上传者阻塞；用户要求120条面向新UGC上传者的第一人称、社区/工会/校园/本地活动查询，保持uploader cap、1至5人、来源门、0.440最大相似度和150 probe上限。"});DESTINATION.write_text(json.dumps(d,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
if __name__=="__main__":main()
