"""Build 120 additional non-overlapping small-sign queries for v1.23."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; SOURCE=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.22.0.json"; DESTINATION=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.23.0.json"
B={
"en":["eviction court support petition outside legal clinic","free school supplies demand outside family resource center","wheelchair ramp repair complaint outside city permits office","emergency room wait time protest outside hospital entrance","fair taxi licensing petition outside vehicle commission","public toilet repair request outside parks department","safer bike lane sign outside road engineering office","local bus driver break demand outside operations garage","street vendor permit appeal outside market administration","firefighter equipment funding sign outside safety office","after school program petition outside youth center","unpaid internship protest outside university careers office","home energy bill complaint outside utility customer center","public beach access petition outside coastal authority","food delivery safety demand outside courier hub","night nurse transit request outside hospital shuttle stop","classroom ventilation complaint outside school maintenance office","affordable childcare petition outside municipal services center","community broadband access sign outside telecom store","construction dust complaint outside environmental agency"],
"es":["petición de apoyo de tribunal de desalojo frente a clínica legal","demanda de útiles escolares gratis frente a centro familiar","queja de rampa para silla de ruedas frente a oficina de permisos","protesta por espera de urgencias frente a entrada de hospital","petición de licencia justa de taxi frente a comisión de vehículos","solicitud de reparación de baño público frente a parques","cartel de carril bici seguro frente a oficina de ingeniería vial","demanda de descansos de conductor de autobús frente a garaje","apelación de permiso de vendedor frente a administración de mercado","cartel de financiación de equipo de bomberos frente a oficina de seguridad","petición de programa extraescolar frente a centro juvenil","protesta por prácticas sin pago frente a oficina universitaria","queja de factura de energía doméstica frente a centro de clientes","petición de acceso a playa pública frente a autoridad costera","demanda de seguridad de reparto de comida frente a centro de mensajería","solicitud de transporte de enfermera nocturna frente a parada de hospital","queja de ventilación de aula frente a oficina de mantenimiento escolar","petición de cuidado infantil asequible frente a centro municipal","cartel de acceso a internet comunitario frente a tienda de telecomunicaciones","queja de polvo de construcción frente a agencia ambiental"],
"fr":["pétition soutien tribunal expulsion devant clinique juridique","demande fournitures scolaires gratuites devant centre familles","plainte rampe fauteuil roulant devant bureau permis","protestation attente urgences devant entrée hôpital","pétition licence taxi équitable devant commission véhicules","demande réparation toilettes publiques devant parcs","pancarte piste vélo sûre devant bureau ingénierie route","demande pauses conducteur bus devant garage opérations","appel permis vendeur rue devant administration marché","pancarte financement équipement pompiers devant bureau sécurité","pétition programme après école devant centre jeunesse","protestation stage impayé devant bureau carrières université","plainte facture énergie domicile devant centre clients","pétition accès plage publique devant autorité côtière","demande sécurité livraison repas devant centre coursiers","demande transport infirmière nuit devant arrêt navette hôpital","plainte ventilation classe devant maintenance école","pétition garde enfants abordable devant centre municipal","pancarte accès internet quartier devant magasin télécom","plainte poussière chantier devant agence environnement"]}
A={"en":["phone video","vertical video","short video","mobile video","#shorts"],"es":["vídeo móvil","vídeo vertical","video corto","vídeo móvil","shorts"],"fr":["vidéo mobile","vidéo verticale","vidéo courte","vidéo mobile","shorts"]}; P={"en":["one person holding","two people holding"],"es":["una persona con","dos personas con"],"fr":["une personne avec","deux personnes avec"]}; W={"en":"protest sign banner","es":"cartel pancarta de protesta","fr":"pancarte banderole de protestation"}
def main():
 d=json.loads(SOURCE.read_text(encoding="utf-8")); qs=[]
 for lang,items in B.items():
  i=0
  for base in items:
   for p in P[lang]:
    i+=1; a=A[lang][(i-1)%5]; action=f"{p} {W[lang]} {base}"; qs.append({"query_id":f"sav123-sign-banner-{lang}-{i:02d}","campaign_id":"sign_action_v1","subtype":"举牌/横幅","lang":lang,"query":f"{action} {a}","source_anchor":a,"source_pool":"mobile_adjacent","action_or_scene_term":action,"rationale_zh":"从冻结的1至5人直接举牌/横幅定义派生未覆盖的住房、医疗、交通、教育、环境和公共服务诉求；单人与两人表达各覆盖，每条含手机或短视频来源锚点，保持来源门、原始0.440多查询最大相似度门和大规模硬排除。"})
 assert len(qs)==120
 c=json.dumps(qs,ensure_ascii=False,sort_keys=True,separators=(",",":"))+"\n"; d.update({"query_pack_version":"sign_action_v1.qp.v1.23.0","queries":qs,"content_sha256":hashlib.sha256(c.encode()).hexdigest(),"created_at":"2026-08-28T11:00:00Z","frozen_at":"2026-08-28","frozen_by":"derived_from_frozen_user_concepts","revision_from":"sign_action_v1.qp.v1.22.0","revision_reason":"用户要求约120条不复用v1.18-v1.22文本的新查询；保持1至5人、来源门、0.440最大相似度和150 probe上限。"}); DESTINATION.write_text(json.dumps(d,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
if __name__=="__main__":main()
