"""Build 120 fresh multilingual small-sign discovery queries for v1.22."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; SOURCE=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.21.0.json"; DESTINATION=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.22.0.json"
BASE={
"en":["public housing repair petition outside housing authority","emergency rent aid complaint at assistance center","accessible elevator request outside metro office","night shift pay demand outside distribution center","safe crossings petition outside traffic bureau","school meal quality complaint at education office","clean drinking water demand outside water utility","domestic violence services petition outside community clinic","mental health funding sign outside health ministry office","disability benefits appeal outside social security office","street lighting repair complaint outside public works office","affordable groceries protest outside food cooperative","senior bus pass petition outside transit depot","library hours demand outside branch library","neighborhood tree protection sign outside planning office","fair scheduling demand outside retail headquarters","safe staffing petition outside care home","student debt relief sign outside financial aid office","workers compensation appeal outside labor board","community clinic access protest outside medical center"],
"es":["petición de reparación de vivienda pública frente a autoridad de vivienda","queja de ayuda urgente de alquiler en centro de asistencia","solicitud de ascensor accesible frente a oficina de metro","demanda de pago de turno nocturno frente a centro de distribución","petición de cruces seguros frente a oficina de tráfico","queja de comidas escolares en oficina de educación","demanda de agua potable frente a empresa de agua","petición de servicios contra violencia doméstica frente a clínica comunitaria","cartel de financiación de salud mental frente a oficina sanitaria","apelación de beneficios por discapacidad frente a seguridad social","queja de alumbrado público frente a oficina de obras","protesta por alimentos asequibles frente a cooperativa","petición de pase de autobús para mayores frente a depósito","demanda de horarios de biblioteca frente a biblioteca","cartel de protección de árboles frente a oficina de planificación","demanda de horarios justos frente a sede comercial","petición de personal seguro frente a residencia de cuidado","cartel de alivio de deuda estudiantil frente a ayuda financiera","apelación de compensación laboral frente a junta laboral","protesta de acceso a clínica comunitaria frente a centro médico"],
"fr":["pétition réparation logement public devant autorité logement","plainte aide urgente loyer centre assistance","demande ascenseur accessible devant bureau métro","demande paiement travail nuit devant centre distribution","pétition passages sûrs devant bureau circulation","plainte repas école devant bureau éducation","demande eau potable devant service eau","pétition services violence domestique devant clinique communautaire","pancarte financement santé mentale devant bureau santé","appel prestations handicap devant sécurité sociale","plainte éclairage rue devant travaux publics","protestation aliments abordables devant coopérative","pétition carte bus seniors devant dépôt transport","demande horaires bibliothèque devant bibliothèque","pancarte protection arbres devant bureau urbanisme","demande horaires équitables devant siège commerce","pétition personnel sûr devant maison soins","pancarte allégement dette étudiante devant aide financière","appel indemnisation travail devant conseil travail","protestation accès clinique communautaire devant centre médical"]}
ANCH={"en":["phone video","vertical video","short video","mobile video","#shorts"],"es":["vídeo móvil","vídeo vertical","video corto","vídeo móvil","shorts"],"fr":["vidéo mobile","vidéo verticale","vidéo courte","vidéo mobile","shorts"]}
PREFIX={"en":["one person holding","two people holding"],"es":["una persona con","dos personas con"],"fr":["une personne avec","deux personnes avec"]}
SIGN_WORDS={"en":"protest sign banner","es":"cartel pancarta de protesta","fr":"pancarte banderole de protestation"}
def main():
 d=json.loads(SOURCE.read_text(encoding="utf-8")); qs=[]
 for lang,bases in BASE.items():
  i=0
  for base in bases:
   for pref in PREFIX[lang]:
    i+=1; anchor=ANCH[lang][(i-1)%5]; action=f"{pref} {SIGN_WORDS[lang]} {base}"; query=f"{action} {anchor}"
    qs.append({"query_id":f"sav122-sign-banner-{lang}-{i:02d}","campaign_id":"sign_action_v1","subtype":"举牌/横幅","lang":lang,"query":query,"source_anchor":anchor,"source_pool":"mobile_adjacent","action_or_scene_term":action,"rationale_zh":"从冻结的1至5人直接举牌/横幅定义派生新的具体诉求、职业关联、机构和地点组合；以单人和两人表达扩展覆盖，每条含手机或短视频来源锚点，保持来源门、原始0.440多查询最大相似度门及大规模硬排除。"})
 assert len(qs)==120
 c=json.dumps(qs,ensure_ascii=False,sort_keys=True,separators=(",",":"))+"\n"; d.update({"query_pack_version":"sign_action_v1.qp.v1.22.0","queries":qs,"content_sha256":hashlib.sha256(c.encode()).hexdigest(),"created_at":"2026-08-28T10:00:00Z","frozen_at":"2026-08-28","frozen_by":"derived_from_frozen_user_concepts","revision_from":"sign_action_v1.qp.v1.21.0","revision_reason":"用户要求约120条不重复查询以扩大具体诉求、职业、地点及单人/两人/小组覆盖；保持1至5人、来源门、0.440最大相似度和150 probe上限。"}); DESTINATION.write_text(json.dumps(d,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
if __name__=="__main__":main()
