"""Create a distinct frozen 1--5 participant sign long-tail query pack."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; SOURCE=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.16.0.json"; DESTINATION=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.17.0.json"
Q=(("en","one person holding protest sign outside train station phone video","phone video","one person holding protest sign outside train station"),("en","two workers with picket signs outside hospital loading dock vertical video","vertical video","two workers with picket signs outside hospital loading dock"),("en","small group displaying petition banner outside courthouse plaza short video","short video","small group displaying petition banner outside courthouse plaza"),("en","resident holding utility complaint placard outside city hall mobile video","mobile video","resident holding utility complaint placard outside city hall"),("en","two people holding protest signs outside school board office phone video","phone video","two people holding protest signs outside school board office"),("es","una persona con cartel de protesta frente a estación de tren vídeo móvil","vídeo móvil","una persona con cartel de protesta frente a estación de tren"),("es","dos trabajadores con carteles de piquete frente a muelle de hospital vídeo vertical","vídeo vertical","dos trabajadores con carteles de piquete frente a muelle de hospital"),("es","grupo pequeño mostrando pancarta de petición frente a plaza del juzgado video corto","video corto","grupo pequeño mostrando pancarta de petición frente a plaza del juzgado"),("es","residente con cartel de queja de servicios frente a ayuntamiento vídeo móvil","vídeo móvil","residente con cartel de queja de servicios frente a ayuntamiento"),("es","dos personas con carteles de protesta frente a oficina de consejo escolar vídeo móvil","vídeo móvil","dos personas con carteles de protesta frente a oficina de consejo escolar"),("fr","une personne avec pancarte de protestation devant gare vidéo mobile","vidéo mobile","une personne avec pancarte de protestation devant gare"),("fr","deux travailleurs avec pancartes de piquet devant quai hôpital vidéo verticale","vidéo verticale","deux travailleurs avec pancartes de piquet devant quai hôpital"),("fr","petit groupe montrant banderole pétition devant place tribunal vidéo courte","vidéo courte","petit groupe montrant banderole pétition devant place tribunal"),("fr","résident avec pancarte plainte services devant mairie vidéo mobile","vidéo mobile","résident avec pancarte plainte services devant mairie"),("fr","deux personnes avec pancartes protestation devant bureau conseil scolaire vidéo mobile","vidéo mobile","deux personnes avec pancartes protestation devant bureau conseil scolaire"))
def main():
 d=json.loads(SOURCE.read_text(encoding="utf-8")); n={"en":0,"es":0,"fr":0}; qs=[]
 for lang,q,a,t in Q:
  n[lang]+=1; qs.append({"query_id":f"sav117-sign-banner-{lang}-{n[lang]:02d}","campaign_id":"sign_action_v1","subtype":"举牌/横幅","lang":lang,"query":q,"source_anchor":a,"source_pool":"mobile_adjacent","action_or_scene_term":t,"rationale_zh":"从冻结的1至5人直接举牌定义派生车站、医院装卸区、法院广场、市政厅和教育服务长尾场景；保持来源门、原始0.440多查询最大相似度门及大规模硬排除。"})
 canonical=json.dumps(qs,ensure_ascii=False,sort_keys=True,separators=(",",":"))+"\n"; d.update({"query_pack_version":"sign_action_v1.qp.v1.17.0","queries":qs,"content_sha256":hashlib.sha256(canonical.encode()).hexdigest(),"created_at":"2026-08-28T05:00:00Z","frozen_at":"2026-08-28","frozen_by":"derived_from_frozen_user_concepts","revision_from":"sign_action_v1.qp.v1.16.0","revision_reason":"当前多查询激活Frontier耗尽；仅扩展未覆盖小规模举牌地点，不降低原始0.440最大相似度门或来源门。"}); DESTINATION.write_text(json.dumps(d,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
if __name__=="__main__": main()
