"""Build a 60-query multilingual, small-scale mobile-sign discovery pack."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
SOURCE=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.17.0.json"
DESTINATION=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.18.0.json"
SCENES={
"en":["one union worker holding picket sign factory gate","two tenants holding rent protest signs housing office","small group students holding tuition banner school entrance","one nurse holding hospital staffing sign clinic entrance","two teachers holding education protest signs school board","small climate group holding banner city hall","one animal rights protester holding sign outside store","two people holding boycott signs supermarket entrance","small group holding community complaint banner council office","one person holding petition sign courthouse plaza","two workers holding wage protest banner warehouse gate","one tenant holding eviction protest sign apartment entrance","small group holding transit complaint banner station entrance","one student holding campus petition sign university gate","two nurses holding patient safety banner hospital gate","one teacher holding school funding sign district office","small group holding clean air banner factory entrance","two people holding consumer complaint signs utility office","one resident holding neighborhood petition sign community center","small group holding workers rights banner delivery depot"],
"es":["un trabajador sindical con cartel de piquete en puerta de fábrica","dos inquilinos con carteles de alquiler frente a oficina de vivienda","grupo pequeño de estudiantes con pancarta de matrícula en entrada de escuela","una enfermera con cartel de personal hospitalario en entrada de clínica","dos profesores con carteles de educación frente a consejo escolar","grupo pequeño por el clima con pancarta en ayuntamiento","una persona por derechos animales con cartel fuera de tienda","dos personas con carteles de boicot en entrada de supermercado","grupo pequeño con pancarta de queja comunitaria en oficina municipal","una persona con cartel de petición en plaza del juzgado","dos trabajadores con pancarta salarial en puerta de almacén","un inquilino con cartel contra desalojo en entrada de apartamento","grupo pequeño con pancarta de transporte en entrada de estación","un estudiante con cartel de petición en puerta universitaria","dos enfermeras con pancarta de seguridad en puerta de hospital","un profesor con cartel de financiación escolar en oficina distrital","grupo pequeño con pancarta de aire limpio en entrada de fábrica","dos personas con carteles de queja de consumidores en oficina de servicios","un residente con cartel de petición vecinal en centro comunitario","grupo pequeño con pancarta de derechos laborales en depósito de reparto"],
"fr":["un travailleur syndical avec pancarte de piquet au portail usine","deux locataires avec pancartes de loyer devant bureau logement","petit groupe étudiants avec banderole frais entrée école","une infirmière avec pancarte personnel hôpital entrée clinique","deux enseignants avec pancartes éducation devant conseil scolaire","petit groupe climat avec banderole devant mairie","une personne droits animaux avec pancarte devant magasin","deux personnes avec pancartes boycott entrée supermarché","petit groupe avec banderole plainte communautaire bureau municipal","une personne avec pancarte pétition place tribunal","deux travailleurs avec banderole salaire portail entrepôt","un locataire avec pancarte contre expulsion entrée immeuble","petit groupe avec banderole transport entrée gare","un étudiant avec pancarte pétition portail université","deux infirmières avec banderole sécurité portail hôpital","un enseignant avec pancarte financement école bureau district","petit groupe avec banderole air propre entrée usine","deux personnes avec pancartes plainte consommateurs bureau services","un résident avec pancarte pétition quartier centre communautaire","petit groupe avec banderole droits travailleurs dépôt livraison"]}
ANCHORS={"en":["phone video","vertical video","short video","mobile video","#shorts"],"es":["vídeo móvil","vídeo vertical","video corto","vídeo móvil","shorts"],"fr":["vidéo mobile","vidéo verticale","vidéo courte","vidéo mobile","shorts"]}
def main():
 d=json.loads(SOURCE.read_text(encoding="utf-8")); qs=[]
 for lang,scenes in SCENES.items():
  for i,scene in enumerate(scenes,1):
   anchor=ANCHORS[lang][(i-1)%len(ANCHORS[lang])]; query=f"{scene} {anchor}"
   qs.append({"query_id":f"sav118-sign-banner-{lang}-{i:02d}","campaign_id":"sign_action_v1","subtype":"举牌/横幅","lang":lang,"query":query,"source_anchor":anchor,"source_pool":"mobile_adjacent","action_or_scene_term":scene,"rationale_zh":"从冻结的1至5人直接举牌/横幅定义派生身份、诉求与地点组合；每条均带手机或短视频来源锚点，保持来源门、原始0.440多查询最大相似度门与大规模硬排除。"})
 canonical=json.dumps(qs,ensure_ascii=False,sort_keys=True,separators=(",",":"))+"\n"
 d.update({"query_pack_version":"sign_action_v1.qp.v1.18.0","queries":qs,"content_sha256":hashlib.sha256(canonical.encode()).hexdigest(),"created_at":"2026-08-28T06:00:00Z","frozen_at":"2026-08-28","frozen_by":"derived_from_frozen_user_concepts","revision_from":"sign_action_v1.qp.v1.17.0","revision_reason":"v1.17仅新增3条技术成功下载；用户要求扩大为60条多样化身份/诉求/地点组合，但保持1至5人、手机来源、原始0.440门与150 probe上限。"})
 DESTINATION.write_text(json.dumps(d,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
if __name__=="__main__":main()
