"""Build non-overlapping multilingual small-sign combinations for v1.19."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; SOURCE=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.18.0.json"; DESTINATION=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.19.0.json"
S={
"en":["one gig worker holding delivery pay sign outside app office","two parents holding school safety banner outside academy","small disability rights group holding access signs at metro entrance","one refugee advocate holding asylum sign outside embassy","two farmers holding water rights banner outside market","small library supporters group holding funding signs city library","one pensioner holding benefits complaint sign social services office","two artists holding culture funding banner theatre entrance","small healthcare advocates group holding medicine cost signs pharmacy","one cyclist holding road safety sign transport office","two volunteers holding food aid banner council plaza","small veterans group holding housing petition office entrance","one shopper holding fair price sign retail store entrance","two caregivers holding care pay banner nursing home gate","small youth group holding voting rights signs election office","one resident holding noise complaint placard construction site gate","two delivery riders holding contract banner logistics hub","small faith group holding peace signs community hall","one parent holding childcare petition sign daycare entrance","two local workers holding jobs banner industrial park gate"],
"es":["un repartidor con cartel de pago frente a oficina de aplicación","dos padres con pancarta de seguridad escolar frente a academia","grupo pequeño por derechos discapacidad con carteles de acceso en entrada de metro","una persona por refugiados con cartel de asilo frente a embajada","dos agricultores con pancarta de derechos de agua frente a mercado","grupo pequeño de apoyo a biblioteca con carteles de financiación en biblioteca","un jubilado con cartel de queja de prestaciones en servicios sociales","dos artistas con pancarta de financiación cultural en entrada de teatro","grupo pequeño de salud con carteles de costo de medicina frente a farmacia","un ciclista con cartel de seguridad vial en oficina de transporte","dos voluntarios con pancarta de ayuda alimentaria en plaza municipal","grupo pequeño de veteranos con petición de vivienda en entrada de oficina","un comprador con cartel de precio justo en entrada de tienda","dos cuidadores con pancarta de salario en puerta de residencia","grupo pequeño de jóvenes con carteles de derecho al voto en oficina electoral","un residente con cartel de queja de ruido en puerta de obra","dos repartidores con pancarta de contrato en centro logístico","grupo pequeño de fe con carteles de paz en salón comunitario","un padre con cartel de petición de guardería en entrada de centro infantil","dos trabajadores locales con pancarta de empleo en puerta de parque industrial"],
"fr":["un livreur avec pancarte salaire devant bureau application","deux parents avec banderole sécurité école devant académie","petit groupe droits handicap avec pancartes accès entrée métro","une personne soutien réfugiés avec pancarte asile devant ambassade","deux agriculteurs avec banderole droits eau devant marché","petit groupe soutien bibliothèque avec pancartes financement bibliothèque","un retraité avec pancarte plainte prestations bureau social","deux artistes avec banderole financement culture entrée théâtre","petit groupe santé avec pancartes coût médicaments devant pharmacie","un cycliste avec pancarte sécurité route bureau transport","deux bénévoles avec banderole aide alimentaire place mairie","petit groupe vétérans avec pétition logement entrée bureau","un client avec pancarte prix juste entrée magasin","deux aidants avec banderole salaire portail maison retraite","petit groupe jeunes avec pancartes droit vote bureau élections","un résident avec pancarte plainte bruit portail chantier","deux livreurs avec banderole contrat centre logistique","petit groupe religieux avec pancartes paix salle communautaire","un parent avec pancarte pétition garderie entrée crèche","deux travailleurs locaux avec banderole emplois portail parc industriel"]}
A={"en":["phone video","vertical video","short video","mobile video","#shorts"],"es":["vídeo móvil","vídeo vertical","video corto","vídeo móvil","shorts"],"fr":["vidéo mobile","vidéo verticale","vidéo courte","vidéo mobile","shorts"]}
def main():
 d=json.loads(SOURCE.read_text(encoding="utf-8")); qs=[]
 for lang,items in S.items():
  for i,item in enumerate(items,1):
   a=A[lang][(i-1)%5]; qs.append({"query_id":f"sav119-sign-banner-{lang}-{i:02d}","campaign_id":"sign_action_v1","subtype":"举牌/横幅","lang":lang,"query":f"{item} {a}","source_anchor":a,"source_pool":"mobile_adjacent","action_or_scene_term":item,"rationale_zh":"从冻结的1至5人直接举牌/横幅定义派生全新身份、诉求与地点组合；每条包含手机或短视频来源锚点，保持来源门、原始0.440多查询最大相似度门与大规模硬排除。"})
 c=json.dumps(qs,ensure_ascii=False,sort_keys=True,separators=(",",":"))+"\n"; d.update({"query_pack_version":"sign_action_v1.qp.v1.19.0","queries":qs,"content_sha256":hashlib.sha256(c.encode()).hexdigest(),"created_at":"2026-08-28T07:00:00Z","frozen_at":"2026-08-28","frozen_by":"derived_from_frozen_user_concepts","revision_from":"sign_action_v1.qp.v1.18.0","revision_reason":"v1.18池耗尽；用户要求60条不复用文本的身份/诉求/地点组合，仍维持1至5人、来源门、0.440最大相似度和150 probe上限。"}); DESTINATION.write_text(json.dumps(d,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
if __name__=="__main__":main()
