"""Build 120 distinct 1--5 participant mobile-sign queries for v1.27."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];SOURCE=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.26.0.json";DESTINATION=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.27.0.json"
B={
"en":["water treatment operator holding staffing sign filtration plant gate","two park maintenance workers holding equipment banner municipal nursery","small apartment cleaners group holding wage petition property office","one ferry passenger holding schedule complaint sign dock terminal","two emergency dispatchers holding workload banner call center entrance","small home delivery couriers group holding rain gear signs depot gate","one prison visitor advocate holding family access placard justice office","two dental assistants holding sick leave banner clinic entrance","small street artists group holding permit protest signs pedestrian plaza","one landfill worker holding protective gear sign waste site office","two school bus aides holding safety banner transportation garage","small community gardeners group holding soil cleanup petition brownfield office","one public defender client holding hearing access sign courthouse annex","two restaurant servers holding tip policy banner dining district","small disabled students group holding exam access signs college hall","one animal control worker holding staffing placard shelter office","two factory trainees holding apprenticeship banner employment center","small coastal residents group holding flood barrier signs harbor authority","one neighborhood mediator holding peace funding sign civic center","two warehouse loaders holding lifting safety banner freight dock"],
"es":["operador de tratamiento de agua con cartel de personal en planta de filtración","dos trabajadores de parques con pancarta de equipo en vivero municipal","grupo pequeño de limpiadores de apartamentos con petición salarial en oficina","un pasajero de ferry con cartel de horarios en terminal de muelle","dos despachadores de emergencias con pancarta de carga en centro de llamadas","grupo pequeño de repartidores con carteles de equipo de lluvia en depósito","una persona por visitas de prisión con cartel de acceso familiar en justicia","dos asistentes dentales con pancarta de baja médica en clínica","grupo pequeño de artistas callejeros con carteles de permiso en plaza peatonal","un trabajador de vertedero con cartel de protección en oficina de residuos","dos asistentes de autobús escolar con pancarta de seguridad en garaje","grupo pequeño de jardineros con petición de suelo limpio en oficina industrial","un cliente de defensor público con cartel de audiencia en anexo judicial","dos camareros con pancarta de propinas en distrito de restaurantes","grupo pequeño de estudiantes con discapacidad con carteles de exámenes en universidad","un trabajador de control animal con cartel de personal en refugio","dos aprendices de fábrica con pancarta de formación en centro de empleo","grupo pequeño costero con carteles de barrera contra inundación en puerto","un mediador vecinal con cartel de paz en centro cívico","dos cargadores de almacén con pancarta de levantamiento seguro en muelle"],
"fr":["opérateur traitement eau avec pancarte personnel portail filtration","deux agents parcs avec banderole matériel pépinière municipale","petit groupe nettoyeurs appartements avec pétition salaire bureau propriété","un passager ferry avec pancarte horaires terminal quai","deux répartiteurs urgences avec banderole charge centre appels","petit groupe coursiers domicile avec pancartes équipement pluie portail dépôt","une personne défense visiteurs prison avec pancarte accès famille bureau justice","deux assistantes dentaires avec banderole congé maladie entrée clinique","petit groupe artistes rue avec pancartes permis place piétonne","un ouvrier décharge avec pancarte équipement protection bureau déchets","deux aides bus scolaire avec banderole sécurité garage transport","petit groupe jardiniers quartier avec pétition dépollution sol bureau friche","un client défense publique avec pancarte accès audience annexe tribunal","deux serveurs restaurant avec banderole politique pourboires quartier repas","petit groupe étudiants handicap avec pancartes accès examens hall université","un agent contrôle animaux avec pancarte personnel bureau refuge","deux stagiaires usine avec banderole apprentissage centre emploi","petit groupe résidents côtiers avec pancartes digue inondation autorité port","un médiateur quartier avec pancarte financement paix centre civique","deux chargeurs entrepôt avec banderole levage sûr quai fret"]}
A={"en":["phone video","vertical video","short video","mobile video","#shorts"],"es":["vídeo móvil","vídeo vertical","video corto","vídeo móvil","shorts"],"fr":["vidéo mobile","vidéo verticale","vidéo courte","vidéo mobile","shorts"]};P={"en":["one person holding","two people holding"],"es":["una persona con","dos personas con"],"fr":["une personne avec","deux personnes avec"]};W={"en":"protest sign banner","es":"cartel pancarta de protesta","fr":"pancarte banderole de protestation"}
def main():
 d=json.loads(SOURCE.read_text(encoding="utf-8"));qs=[]
 for lang,items in B.items():
  i=0
  for b in items:
   for p in P[lang]:
    i+=1;a=A[lang][(i-1)%5];act=f"{p} {W[lang]} {b}";qs.append({"query_id":f"sav127-sign-banner-{lang}-{i:02d}","campaign_id":"sign_action_v1","subtype":"举牌/横幅","lang":lang,"query":f"{act} {a}","source_anchor":a,"source_pool":"mobile_adjacent","action_or_scene_term":act,"rationale_zh":"从冻结的1至5人直接举牌/横幅定义派生新的公用设施、职业、安全、环境、司法和交通诉求；每条含手机或短视频锚点，保持来源门、原始0.440多查询最大相似度门和全部硬排除。"})
 assert len(qs)==120
 c=json.dumps(qs,ensure_ascii=False,sort_keys=True,separators=(",",":"))+"\n";d.update({"query_pack_version":"sign_action_v1.qp.v1.27.0","queries":qs,"content_sha256":hashlib.sha256(c.encode()).hexdigest(),"created_at":"2026-08-28T14:00:00Z","frozen_at":"2026-08-28","frozen_by":"derived_from_frozen_user_concepts","revision_from":"sign_action_v1.qp.v1.26.0","revision_reason":"用户要求120条不与历史文本重复的职业、诉求、机构和设施组合；保持1至5人、来源门、0.440最大相似度和150 probe上限。"});DESTINATION.write_text(json.dumps(d,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
if __name__=="__main__":main()
