"""Derive a further frozen long-tail 1--5 participant sign query pack."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; SOURCE=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.15.0.json"; DESTINATION=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.16.0.json"
Q=(("en","one person holding protest sign outside fire station phone video","phone video","one person holding protest sign outside fire station"),("en","two workers holding picket signs outside water plant vertical video","vertical video","two workers holding picket signs outside water plant"),("en","small group displaying petition banner outside courthouse short video","short video","small group displaying petition banner outside courthouse"),("en","resident holding service complaint placard outside city office mobile video","mobile video","resident holding service complaint placard outside city office"),("en","two people holding protest signs outside parking authority phone video","phone video","two people holding protest signs outside parking authority"),("es","una persona con cartel de protesta frente a estación de bomberos vídeo móvil","vídeo móvil","una persona con cartel de protesta frente a estación de bomberos"),("es","dos trabajadores con carteles de piquete frente a planta de agua vídeo vertical","vídeo vertical","dos trabajadores con carteles de piquete frente a planta de agua"),("es","grupo pequeño mostrando pancarta de petición frente al juzgado video corto","video corto","grupo pequeño mostrando pancarta de petición frente al juzgado"),("es","residente con cartel de queja de servicios frente a oficina municipal vídeo móvil","vídeo móvil","residente con cartel de queja de servicios frente a oficina municipal"),("es","dos personas con carteles de protesta frente a autoridad de estacionamiento vídeo móvil","vídeo móvil","dos personas con carteles de protesta frente a autoridad de estacionamiento"),("fr","une personne avec pancarte de protestation devant caserne pompiers vidéo mobile","vidéo mobile","une personne avec pancarte de protestation devant caserne pompiers"),("fr","deux travailleurs avec pancartes de piquet devant usine eau vidéo verticale","vidéo verticale","deux travailleurs avec pancartes de piquet devant usine eau"),("fr","petit groupe montrant banderole de pétition devant tribunal vidéo courte","vidéo courte","petit groupe montrant banderole de pétition devant tribunal"),("fr","résident avec pancarte plainte services devant bureau ville vidéo mobile","vidéo mobile","résident avec pancarte plainte services devant bureau ville"),("fr","deux personnes avec pancartes protestation devant autorité stationnement vidéo mobile","vidéo mobile","deux personnes avec pancartes protestation devant autorité stationnement"))
def main():
 d=json.loads(SOURCE.read_text(encoding="utf-8")); n={"en":0,"es":0,"fr":0}; qs=[]
 for lang,q,a,t in Q:
  n[lang]+=1; qs.append({"query_id":f"sav116-sign-banner-{lang}-{n[lang]:02d}","campaign_id":"sign_action_v1","subtype":"举牌/横幅","lang":lang,"query":q,"source_anchor":a,"source_pool":"mobile_adjacent","action_or_scene_term":t,"rationale_zh":"从冻结的1至5人直接举牌定义派生消防站、水厂、法院、市政服务和停车管理长尾场景；保持来源门、0.440原始语义门及大规模硬排除。"})
 canonical=json.dumps(qs,ensure_ascii=False,sort_keys=True,separators=(",",":"))+"\n"; d.update({"query_pack_version":"sign_action_v1.qp.v1.16.0","queries":qs,"content_sha256":hashlib.sha256(canonical.encode()).hexdigest(),"created_at":"2026-08-28T04:00:00Z","frozen_at":"2026-08-28","frozen_by":"derived_from_frozen_user_concepts","revision_from":"sign_action_v1.qp.v1.15.0","revision_reason":"v1.15仅形成3条技术成功下载；仅增加未覆盖长尾地点，不降低任一门槛。"}); DESTINATION.write_text(json.dumps(d,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
if __name__=="__main__": main()
