"""Build a fresh v1.21 multilingual small-sign discovery pack."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; SOURCE=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.20.0.json"; DESTINATION=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.21.0.json"
S={
"en":["one paramedic holding ambulance staffing sign emergency center","two childcare workers holding leave policy banner daycare office","small homecare workers group holding pay signs care agency entrance","one bus rider holding route restoration placard transit center","two public defenders holding legal aid banner courthouse steps","small neighborhood gardeners group holding park water signs recreation office","one airport cleaner holding contract sign terminal service entrance","two museum guides holding wage banner cultural center gate","small dialysis patients group holding treatment signs health board office","one dock worker holding shift safety placard shipping terminal","two translators holding language service banner immigration office","small music teachers group holding lesson funding signs arts council","one recycling worker holding equipment safety sign waste transfer station","two cafeteria workers holding meal program banner school kitchen","small flood victims group holding repair petition insurance office","one tenant organizer holding heat complaint sign building management entrance","two nurses aides holding staffing banner rehabilitation center","small parents group holding special education signs district meeting hall","one warehouse driver holding rest break placard freight gate","two librarians holding public access banner branch library entrance"],
"es":["un paramédico con cartel de personal de ambulancia en centro de emergencias","dos trabajadores infantiles con pancarta de permisos en oficina de guardería","grupo pequeño de cuidadores domiciliarios con carteles de pago en agencia de cuidado","un usuario de autobús con cartel de restauración de ruta en centro de transporte","dos defensores públicos con pancarta de ayuda legal en escaleras del juzgado","grupo pequeño de jardineros vecinales con carteles de agua de parque en oficina recreativa","un limpiador de aeropuerto con cartel de contrato en entrada de terminal","dos guías de museo con pancarta salarial en puerta de centro cultural","grupo pequeño de pacientes de diálisis con carteles de tratamiento en oficina de salud","un estibador con cartel de seguridad de turno en terminal marítima","dos traductores con pancarta de servicio lingüístico en oficina de inmigración","grupo pequeño de profesores de música con carteles de financiación en consejo de artes","un trabajador de reciclaje con cartel de seguridad de equipo en estación de residuos","dos trabajadores de cafetería con pancarta de programa de comidas en cocina escolar","grupo pequeño de víctimas de inundación con petición de reparación en oficina de seguros","un organizador de inquilinos con cartel de queja de calefacción en entrada de gestión","dos auxiliares de enfermería con pancarta de personal en centro de rehabilitación","grupo pequeño de padres con carteles de educación especial en salón distrital","un conductor de almacén con cartel de descansos en puerta de carga","dos bibliotecarios con pancarta de acceso público en entrada de biblioteca"],
"fr":["un ambulancier avec pancarte personnel ambulance centre urgences","deux travailleurs petite enfance avec banderole congés bureau crèche","petit groupe aides domicile avec pancartes salaire entrée agence soins","un usager bus avec pancarte retour ligne centre transport","deux défenseurs publics avec banderole aide juridique marches tribunal","petit groupe jardiniers quartier avec pancartes eau parc bureau loisirs","un nettoyeur aéroport avec pancarte contrat entrée terminal","deux guides musée avec banderole salaire portail centre culturel","petit groupe patients dialyse avec pancartes traitement bureau santé","un docker avec pancarte sécurité quart terminal maritime","deux traducteurs avec banderole service langue bureau immigration","petit groupe professeurs musique avec pancartes financement conseil arts","un agent recyclage avec pancarte sécurité matériel station déchets","deux employés cafétéria avec banderole repas cuisine école","petit groupe victimes inondation avec pétition réparation bureau assurance","un organisateur locataires avec pancarte chauffage entrée gestion immeuble","deux aides soignants avec banderole personnel centre réadaptation","petit groupe parents avec pancartes éducation spécialisée salle district","un conducteur entrepôt avec pancarte pauses portail fret","deux bibliothécaires avec banderole accès public entrée bibliothèque"]}
A={"en":["phone video","vertical video","short video","mobile video","#shorts"],"es":["vídeo móvil","vídeo vertical","video corto","vídeo móvil","shorts"],"fr":["vidéo mobile","vidéo verticale","vidéo courte","vidéo mobile","shorts"]}
def main():
 d=json.loads(SOURCE.read_text(encoding="utf-8")); qs=[]
 for lang,items in S.items():
  for i,item in enumerate(items,1):
   a=A[lang][(i-1)%5]; qs.append({"query_id":f"sav121-sign-banner-{lang}-{i:02d}","campaign_id":"sign_action_v1","subtype":"举牌/横幅","lang":lang,"query":f"{item} {a}","source_anchor":a,"source_pool":"mobile_adjacent","action_or_scene_term":item,"rationale_zh":"从冻结的1至5人直接举牌/横幅定义派生新的职业、公共服务诉求和具体机构地点组合；每条含手机或短视频来源锚点，保持来源门、原始0.440多查询最大相似度门和大规模硬排除。"})
 c=json.dumps(qs,ensure_ascii=False,sort_keys=True,separators=(",",":"))+"\n"; d.update({"query_pack_version":"sign_action_v1.qp.v1.21.0","queries":qs,"content_sha256":hashlib.sha256(c.encode()).hexdigest(),"created_at":"2026-08-28T09:00:00Z","frozen_at":"2026-08-28","frozen_by":"derived_from_frozen_user_concepts","revision_from":"sign_action_v1.qp.v1.20.0","revision_reason":"v1.20池耗尽；用户要求60条不复用v1.18-v1.20文本的新职业、诉求、机构与地点组合，保持1至5人、来源门、0.440最大相似度和150 probe上限。"}); DESTINATION.write_text(json.dumps(d,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
if __name__=="__main__":main()
