"""Build 120 new small-sign queries with distinct occupations and facilities."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];SOURCE=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.25.0.json";DESTINATION=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.26.0.json"
B={
"en":["homeless outreach worker holding shelter funding sign service center","two laboratory technicians holding safety training banner research hospital","small security guards group holding fair pay signs office tower entrance","one crossing guard holding school zone safety placard intersection","two ride share drivers holding insurance banner airport lot","small community nurses group holding clinic hours signs neighborhood health center","one substitute teacher holding contract sign education headquarters","two recycling volunteers holding composting petition waste office","small public housing residents group holding elevator repair banner lobby","one disability caregiver holding respite funding placard care agency","two grocery cashiers holding affordable transit banner shopping plaza","small language students group holding visa processing signs immigration center","one maintenance worker holding boiler repair sign public library","two museum conservators holding climate control banner archive building","small fire victims group holding emergency aid signs disaster office","one legal secretary holding staffing sign court administration","two farm market workers holding weather shelter banner market pavilion","small neighborhood elders group holding sidewalk repair petition street office","one bus mechanic holding parts funding placard transit workshop","two animal shelter staff holding adoption support banner shelter entrance"],
"es":["trabajador de ayuda sin hogar con cartel de fondos de refugio en centro de servicio","dos técnicos de laboratorio con pancarta de formación de seguridad en hospital","grupo pequeño de guardias con carteles de pago justo en entrada de torre","un guardia de cruce con cartel de zona escolar segura en intersección","dos conductores de viaje con pancarta de seguro en lote de aeropuerto","grupo pequeño de enfermeras comunitarias con carteles de horarios de clínica","un maestro sustituto con cartel de contrato en sede educativa","dos voluntarios de reciclaje con petición de compostaje en oficina de residuos","grupo pequeño de residentes de vivienda pública con pancarta de ascensor en vestíbulo","un cuidador de discapacidad con cartel de fondos de relevo en agencia","dos cajeros de supermercado con pancarta de transporte asequible en plaza","grupo pequeño de estudiantes de idiomas con carteles de visado en centro migratorio","un trabajador de mantenimiento con cartel de reparación de caldera en biblioteca","dos conservadores de museo con pancarta de clima en edificio de archivo","grupo pequeño de víctimas de incendio con carteles de ayuda en oficina de desastre","un secretario legal con cartel de personal en administración de tribunal","dos trabajadores de mercado agrícola con pancarta de refugio climático en pabellón","grupo pequeño de mayores vecinales con petición de aceras en oficina local","un mecánico de autobús con cartel de piezas en taller de transporte","dos empleados de refugio animal con pancarta de adopción en entrada"],
"fr":["travailleur aide sans abri avec pancarte financement refuge centre service","deux techniciens laboratoire avec banderole formation sécurité hôpital recherche","petit groupe agents sécurité avec pancartes salaire équitable entrée tour bureaux","un garde passage avec pancarte sécurité zone école intersection","deux chauffeurs covoiturage avec banderole assurance parking aéroport","petit groupe infirmières quartier avec pancartes horaires clinique centre santé","un enseignant remplaçant avec pancarte contrat siège éducation","deux bénévoles recyclage avec pétition compost bureau déchets","petit groupe résidents logement public avec banderole réparation ascenseur hall","un aidant handicap avec pancarte financement répit agence soins","deux caissiers épicerie avec banderole transport abordable place commerces","petit groupe étudiants langues avec pancartes visa centre immigration","un agent entretien avec pancarte réparation chaudière bibliothèque","deux conservateurs musée avec banderole contrôle climat bâtiment archives","petit groupe victimes incendie avec pancartes aide urgence bureau catastrophe","un secrétaire juridique avec pancarte personnel administration tribunal","deux travailleurs marché fermier avec banderole abri météo pavillon","petit groupe aînés quartier avec pétition trottoir bureau rue","un mécanicien bus avec pancarte financement pièces atelier transport","deux employés refuge animaux avec banderole soutien adoption entrée refuge"]}
A={"en":["phone video","vertical video","short video","mobile video","#shorts"],"es":["vídeo móvil","vídeo vertical","video corto","vídeo móvil","shorts"],"fr":["vidéo mobile","vidéo verticale","vidéo courte","vidéo mobile","shorts"]};P={"en":["one person holding","two people holding"],"es":["una persona con","dos personas con"],"fr":["une personne avec","deux personnes avec"]};W={"en":"protest sign banner","es":"cartel pancarta de protesta","fr":"pancarte banderole de protestation"}
def main():
 d=json.loads(SOURCE.read_text(encoding="utf-8"));qs=[]
 for lang,items in B.items():
  i=0
  for b in items:
   for p in P[lang]:
    i+=1;a=A[lang][(i-1)%5];act=f"{p} {W[lang]} {b}";qs.append({"query_id":f"sav126-sign-banner-{lang}-{i:02d}","campaign_id":"sign_action_v1","subtype":"举牌/横幅","lang":lang,"query":f"{act} {a}","source_anchor":a,"source_pool":"mobile_adjacent","action_or_scene_term":act,"rationale_zh":"从冻结的1至5人直接举牌/横幅定义派生新的职业、资金/安全/服务诉求与设施场景；每条含手机或短视频锚点，保持来源门、原始0.440多查询最大相似度门和全部硬排除。"})
 assert len(qs)==120
 c=json.dumps(qs,ensure_ascii=False,sort_keys=True,separators=(",",":"))+"\n";d.update({"query_pack_version":"sign_action_v1.qp.v1.26.0","queries":qs,"content_sha256":hashlib.sha256(c.encode()).hexdigest(),"created_at":"2026-08-28T13:00:00Z","frozen_at":"2026-08-28","frozen_by":"derived_from_frozen_user_concepts","revision_from":"sign_action_v1.qp.v1.25.0","revision_reason":"用户要求120条与此前文本不重复的新职业、具体诉求和设施组合；保持1至5人、来源门、0.440最大相似度和150 probe上限。"});DESTINATION.write_text(json.dumps(d,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
if __name__=="__main__":main()
