"""Derive another non-overlapping 1--5 participant sign query pack."""
from __future__ import annotations
import hashlib, json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; SOURCE=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.14.0.json"; DESTINATION=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.15.0.json"
QUERIES=(
("en","one person holding protest sign outside bank phone video","phone video","one person holding protest sign outside bank"),("en","two workers holding picket signs outside bus garage vertical video","vertical video","two workers holding picket signs outside bus garage"),("en","small group displaying petition banner outside museum short video","short video","small group displaying petition banner outside museum"),("en","resident holding rent protest placard outside housing office mobile video","mobile video","resident holding rent protest placard outside housing office"),("en","two people holding complaint signs outside tax office phone video","phone video","two people holding complaint signs outside tax office"),
("es","una persona con cartel de protesta frente a banco vídeo móvil","vídeo móvil","una persona con cartel de protesta frente a banco"),("es","dos trabajadores con carteles de piquete frente a garaje de autobuses vídeo vertical","vídeo vertical","dos trabajadores con carteles de piquete frente a garaje de autobuses"),("es","grupo pequeño mostrando pancarta de petición frente a museo video corto","video corto","grupo pequeño mostrando pancarta de petición frente a museo"),("es","residente con cartel de protesta por alquiler fuera de oficina de vivienda vídeo móvil","vídeo móvil","residente con cartel de protesta por alquiler fuera de oficina de vivienda"),("es","dos personas con carteles de queja frente a oficina de impuestos vídeo móvil","vídeo móvil","dos personas con carteles de queja frente a oficina de impuestos"),
("fr","une personne avec pancarte de protestation devant banque vidéo mobile","vidéo mobile","une personne avec pancarte de protestation devant banque"),("fr","deux travailleurs avec pancartes de piquet devant garage bus vidéo verticale","vidéo verticale","deux travailleurs avec pancartes de piquet devant garage bus"),("fr","petit groupe montrant banderole de pétition devant musée vidéo courte","vidéo courte","petit groupe montrant banderole de pétition devant musée"),("fr","résident avec pancarte protestation loyer devant bureau logement vidéo mobile","vidéo mobile","résident avec pancarte protestation loyer devant bureau logement"),("fr","deux personnes avec pancartes de plainte devant bureau impôts vidéo mobile","vidéo mobile","deux personnes avec pancartes de plainte devant bureau impôts"),)
def main():
 d=json.loads(SOURCE.read_text(encoding="utf-8")); n={"en":0,"es":0,"fr":0}; qs=[]
 for lang,q,a,t in QUERIES:
  n[lang]+=1; qs.append({"query_id":f"sav115-sign-banner-{lang}-{n[lang]:02d}","campaign_id":"sign_action_v1","subtype":"举牌/横幅","lang":lang,"query":q,"source_anchor":a,"source_pool":"mobile_adjacent","action_or_scene_term":t,"rationale_zh":"从冻结的1至5人直接举牌定义派生银行、公交车库、博物馆、住房和税务服务长尾场景；保持来源门、0.440原始语义门及大规模硬排除。"})
 canonical=json.dumps(qs,ensure_ascii=False,sort_keys=True,separators=(",",":"))+"\n"
 d.update({"query_pack_version":"sign_action_v1.qp.v1.15.0","queries":qs,"content_sha256":hashlib.sha256(canonical.encode()).hexdigest(),"created_at":"2026-08-28T03:00:00Z","frozen_at":"2026-08-28","frozen_by":"derived_from_frozen_user_concepts","revision_from":"sign_action_v1.qp.v1.14.0","revision_reason":"v1.14仅形成3条技术成功下载；仅加入未覆盖长尾地点，不降低任一门槛。"})
 DESTINATION.write_text(json.dumps(d,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
if __name__=="__main__": main()
