"""Build 120 fresh local-UGC 1--5 participant sign combinations for v1.31."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];SOURCE=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.30.0.json";DESTINATION=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.31.0.json"
B={
"en":["my local baker holding fair energy bill sign shop opening","our community drivers holding fuel support banner depot meeting","my college club holding campus housing placard student event","our neighborhood seniors holding clinic shuttle signs library gathering","my coworker holding holiday pay banner service entrance","our small union team holding grievance sign plant parking lot","my friend holding playground shade petition park event","our parent volunteers holding school lunch banner pickup line","my neighbor holding tree trimming complaint sign street meeting","our local trainers holding gym access signs recreation center","my classmate holding disability exam placard college walk","our shop staff holding schedule notice banner mall meetup","my family holding food price complaint sign market visit","our community translators holding language rights signs public office","my coworker holding injury leave placard warehouse entrance","our tenants group holding window repair banner block gathering","my local musicians holding venue access signs sidewalk festival","our student group holding counseling banner campus action","my neighbor holding drainage repair sign rainy street event","our volunteers holding public shelter banner community drive"],
"es":["mi panadero local con cartel de factura de energía en apertura de tienda","nuestros conductores comunitarios con pancarta de combustible reunión de depósito","mi club universitario con cartel de vivienda evento estudiantil","nuestros mayores vecinales con carteles de transporte a clínica reunión de biblioteca","mi compañero con pancarta de pago festivo entrada de servicio","nuestro pequeño equipo sindical con cartel de queja estacionamiento de planta","mi amigo con petición de sombra de parque evento local","nuestros padres voluntarios con pancarta de almuerzo escolar fila de recogida","mi vecino con cartel de poda de árboles reunión de calle","nuestros entrenadores locales con carteles de acceso a gimnasio centro recreativo","mi compañero de clase con cartel de examen accesible paseo universitario","nuestro personal de tienda con pancarta de horarios reunión de centro comercial","mi familia con cartel de precios de comida visita de mercado","nuestros traductores comunitarios con carteles de derechos lingüísticos oficina pública","mi compañero con cartel de baja por lesión entrada de almacén","nuestro grupo de inquilinos con pancarta de ventanas reunión de bloque","mis músicos locales con carteles de acceso a local festival de calle","nuestro grupo estudiantil con pancarta de asesoramiento acción de campus","mi vecino con cartel de reparación de drenaje evento de calle lluviosa","nuestros voluntarios con pancarta de refugio público actividad comunitaria"],
"fr":["mon boulanger local avec pancarte facture énergie ouverture magasin","nos conducteurs communauté avec banderole soutien carburant réunion dépôt","mon club collège avec pancarte logement campus événement étudiant","nos aînés quartier avec pancartes navette clinique réunion bibliothèque","mon collègue avec banderole paie jours fériés entrée service","notre petite équipe syndicale avec pancarte grief parking usine","mon ami avec pétition ombre aire jeux événement parc","nos parents bénévoles avec banderole repas école file ramassage","mon voisin avec pancarte taille arbres réunion rue","nos entraîneurs locaux avec pancartes accès gym centre loisirs","mon camarade avec pancarte examen accessible marche collège","notre personnel magasin avec banderole horaires rencontre centre commercial","ma famille avec pancarte prix nourriture visite marché","nos traducteurs communauté avec pancartes droits langue bureau public","mon collègue avec pancarte congé blessure entrée entrepôt","notre groupe locataires avec banderole réparation fenêtres réunion bloc","mes musiciens locaux avec pancartes accès salle festival rue","notre groupe étudiants avec banderole conseil action campus","mon voisin avec pancarte réparation drainage événement rue pluie","nos bénévoles avec banderole refuge public activité communauté"]}
A={"en":["#shorts","reel","phone video","vertical video","mobile video"],"es":["shorts","reel","vídeo móvil","vídeo vertical","video móvil"],"fr":["shorts","reel","vidéo mobile","vidéo verticale","vidéo téléphone"]};P={"en":["one person","two people"],"es":["una persona","dos personas"],"fr":["une personne","deux personnes"]};W={"en":"holding protest sign banner","es":"con cartel pancarta de protesta","fr":"avec pancarte banderole de protestation"}
def main():
 d=json.loads(SOURCE.read_text(encoding="utf-8"));qs=[]
 for lang,items in B.items():
  i=0
  for b in items:
   for p in P[lang]:
    i+=1;a=A[lang][(i-1)%5];act=f"{p} {W[lang]} {b}";qs.append({"query_id":f"sav131-sign-banner-{lang}-{i:02d}","campaign_id":"sign_action_v1","subtype":"举牌/横幅","lang":lang,"query":f"{act} {a}","source_anchor":a,"source_pool":"mobile_adjacent","action_or_scene_term":act,"rationale_zh":"面向新UGC上传者的第一人称、本地工会/校园/社区活动组合；每条含手机或短视频锚点和1至5人举牌动作，保持uploader cap、来源门、原始0.440最大相似度和全部硬排除。"})
 assert len(qs)==120
 c=json.dumps(qs,ensure_ascii=False,sort_keys=True,separators=(",",":"))+"\n";d.update({"query_pack_version":"sign_action_v1.qp.v1.31.0","queries":qs,"content_sha256":hashlib.sha256(c.encode()).hexdigest(),"created_at":"2026-08-28T18:00:00Z","frozen_at":"2026-08-28","frozen_by":"derived_from_frozen_user_concepts","revision_from":"sign_action_v1.qp.v1.30.0","revision_reason":"用户要求120条不与此前文本重复的UGC新上传者查询；保持uploader cap、1至5人、来源门、0.440最大相似度和150 probe上限。"});DESTINATION.write_text(json.dumps(d,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
if __name__=="__main__":main()
