"""Build v1.20 with fresh profession, grievance, institution, and place pairs."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; SOURCE=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.19.0.json"; DESTINATION=ROOT/"query-packs/sign_action_v1/sign_action_v1.qp.v1.20.0.json"
S={
"en":["one postal worker holding overtime sign outside mail depot","two sanitation workers holding safety banner outside public works yard","small graduate student group holding stipend signs research campus entrance","one restaurant worker holding wage theft placard outside hotel kitchen","two taxi drivers holding fare policy banner airport pickup zone","small fishermen group holding harbor access signs port office","one immigrant rights advocate holding family reunification sign consulate entrance","two pharmacists holding prescription cost banner health agency office","small mothers group holding playground repair signs parks office","one factory apprentice holding training pay sign labor department entrance","two rail workers holding schedule complaint banner station service gate","small renters group holding mold repair petition property management office","one social worker holding caseload sign welfare office","two retail clerks holding break rights banner mall entrance","small farmers market vendors group holding permit signs licensing office","one interpreter holding language access sign courthouse entrance","two electricians holding contract protest banner construction office","small students group holding scholarship signs college administration","one hotel housekeeper holding workload sign hotel lobby","two mechanics holding job security banner auto plant gate"],
"es":["un trabajador postal con cartel de horas extra frente a depósito de correo","dos trabajadores de limpieza con pancarta de seguridad frente a patio de obras públicas","grupo pequeño de posgrado con carteles de beca en entrada de campus investigación","un trabajador de restaurante con cartel de salario robado fuera de cocina de hotel","dos taxistas con pancarta de tarifas en zona de aeropuerto","grupo pequeño de pescadores con carteles de acceso al puerto en oficina portuaria","una persona por derechos migrantes con cartel de reunificación familiar en entrada de consulado","dos farmacéuticos con pancarta de costo de recetas frente a agencia de salud","grupo pequeño de madres con carteles de reparación de parque en oficina de parques","un aprendiz de fábrica con cartel de pago de formación en entrada de trabajo","dos trabajadores ferroviarios con pancarta de horario en puerta de estación","grupo pequeño de inquilinos con petición de moho en oficina de administración","un trabajador social con cartel de carga de casos en oficina social","dos dependientes con pancarta de descansos en entrada de centro comercial","grupo pequeño de vendedores de mercado con carteles de permisos en oficina de licencias","un intérprete con cartel de acceso lingüístico en entrada de juzgado","dos electricistas con pancarta de contrato en oficina de construcción","grupo pequeño de estudiantes con carteles de becas en administración universitaria","una camarera de hotel con cartel de carga laboral en vestíbulo de hotel","dos mecánicos con pancarta de seguridad laboral en puerta de planta automotriz"],
"fr":["un postier avec pancarte heures supplémentaires devant dépôt courrier","deux agents nettoyage avec banderole sécurité devant service travaux publics","petit groupe doctorants avec pancartes allocation entrée campus recherche","un employé restaurant avec pancarte salaire volé devant cuisine hôtel","deux chauffeurs taxi avec banderole tarifs zone aéroport","petit groupe pêcheurs avec pancartes accès port bureau portuaire","une personne droits migrants avec pancarte réunification familiale entrée consulat","deux pharmaciens avec banderole coût ordonnances devant agence santé","petit groupe mères avec pancartes réparation aire jeux bureau parcs","un apprenti usine avec pancarte salaire formation entrée ministère travail","deux cheminots avec banderole horaires portail gare","petit groupe locataires avec pétition moisissure bureau gestion","un travailleur social avec pancarte charge dossiers bureau social","deux vendeurs avec banderole droit pause entrée centre commercial","petit groupe vendeurs marché avec pancartes permis bureau licences","un interprète avec pancarte accès langue entrée tribunal","deux électriciens avec banderole contrat bureau construction","petit groupe étudiants avec pancartes bourses administration université","une femme ménage hôtel avec pancarte charge travail hall hôtel","deux mécaniciens avec banderole sécurité emploi portail usine automobile"]}
A={"en":["phone video","vertical video","short video","mobile video","#shorts"],"es":["vídeo móvil","vídeo vertical","video corto","vídeo móvil","shorts"],"fr":["vidéo mobile","vidéo verticale","vidéo courte","vidéo mobile","shorts"]}
def main():
 d=json.loads(SOURCE.read_text(encoding="utf-8")); qs=[]
 for lang,items in S.items():
  for i,item in enumerate(items,1):
   a=A[lang][(i-1)%5]; qs.append({"query_id":f"sav120-sign-banner-{lang}-{i:02d}","campaign_id":"sign_action_v1","subtype":"举牌/横幅","lang":lang,"query":f"{item} {a}","source_anchor":a,"source_pool":"mobile_adjacent","action_or_scene_term":item,"rationale_zh":"从冻结的1至5人直接举牌/横幅定义派生新的职业、具体诉求、机构和地点组合；每条含手机或短视频来源锚点，保持来源门、原始0.440多查询最大相似度门及大规模硬排除。"})
 c=json.dumps(qs,ensure_ascii=False,sort_keys=True,separators=(",",":"))+"\n"; d.update({"query_pack_version":"sign_action_v1.qp.v1.20.0","queries":qs,"content_sha256":hashlib.sha256(c.encode()).hexdigest(),"created_at":"2026-08-28T08:00:00Z","frozen_at":"2026-08-28","frozen_by":"derived_from_frozen_user_concepts","revision_from":"sign_action_v1.qp.v1.19.0","revision_reason":"v1.19池耗尽；用户要求60条不与v1.18/v1.19复用的新职业、诉求、机构和地点组合，保持1至5人、来源门、0.440最大相似度和150 probe上限。"}); DESTINATION.write_text(json.dumps(d,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
if __name__=="__main__":main()
